apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: nginx
spec:
    template:
        metadata:
            labels:
                app: nginx
        spec:  #especificação do template
           containers:
           - name: nginx 
             image: nginx:1.16-alpine
             ports:
             - containerPort: 80
             #montagem do volume nginx-conf
             volumeMounts:
             - mountPath: /etc/nginx/conf.d 
               name: nginx-conf
               readOnly: true # é um arquivo de configuração, por isso apenas leitura
           volumes: #criação do volume 
           - name: nginx-conf #mesmo nome atribuido na montagem 
             configMap: #podemos criar um volume apartir do configmap (arquivo configmap.yaml)
               name: nginx-conf
               items:
                - key: nginx.conf #name da chave configurada no configmap, irá pegar o value dela e criar o arquivo
                  path: nginx.conf #path e nome do arquivo (Como o volume já é montado na pasta padrão, basta atribuir o name)
