apiVersion: v1
kind: Service
metadata:
    name: nginx-service
spec: # Do tipo loadbalancer para poder gerar ip-externo e poder trabalhar com mais de um pod
    type: LoadBalancer
    ports:
    - port: 80
    selector:
        app: nginx #ira obter todos os pods(containers) que estiverem com essa label
    
